version: "3"
services:
  mkdocs-live:
    command:
      - serve
      - --dev-addr=0.0.0.0:8000
    container_name: mkdocs-live
    entrypoint:
      - mkdocs
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=Europe/London
    expose:
      - 8000/tcp
    image: squidfunk/mkdocs-material:latest
    volumes:
      - /home/andrew/containers/mkdocs-live/icca-documentation:/docs
    working_dir: /docs
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default
