# use DATA_DIR and CONTAINER_DIR to point to the container dir.
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/config:/config
      - ${DATA_DIR}/cache:/cache
      - ${DATA_DIR}/tmp:/tmp
      - ${DATA_DIR}/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - ${DATA_DIR}/ssh:/root/.ssh:ro # SSH settings - use shell script to generate
      # - /home/ubuntu/backup:/repos     # Mount local repos (optional for remote storage)
      - /home/ubuntu/backup/restic:/repos     # Mount local repos (optional for remote storage)
      # - /home/ubuntu/backup/restic-restore:/restore    # Added this as a destination for writing with correct permissions
      - /home/ubuntu/data:/userdata/data  # Mount local paths to backup
      - /home/ubuntu/containers:/userdata/containers  # Mount local paths to backup
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    ports:
      - "9898:9898"
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default 

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default
